import type { Metadata } from "next";
import Sidebar from "./sidebar";
import Profile from "./profile";

export const metadata: Metadata = {
  title: "ExamBro | Dashboard",
  description: "Generated by create next app",
  icons: [],
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex">
      <Sidebar />
      <div className="ml-[204px] mr-[290px] bg-[#fafafa] w-full min-h-screen px-2">
        {children}
      </div>
      <Profile />
    </main>
  );
}
