import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ExamBro | Signup",
  description: "Generated by create next app",
  icons: [],
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="poppins">{children}</main>;
}
